### ISSUE TITLE
Security warning because using both webview Tag and contextIsolation option

### ISSUE THREAD

**Issue by cba85** [cba85/electron-webview#32]
> (electron) Security Warning: A WebContents was just created with both webviewTag and contextIsolation enabled.  This combination is fundamentally less secure and effectively bypasses the protections of contextIsolation.  We strongly recommend you move away from webviews to OOPIF or BrowserView in order for your app to be more secure

**Comment by avxit** [comment]
Any progress? I'm having the same issue but haven't find any solution yet.

**Comment by cba85** [comment]
I am not actually working on this repository.
I will look for a solution in the next weeks.
I hope you will manage to fix this issue quickly. Waiting for your pull request 😃

**Comment by cba85** [comment]
Deprecated since Electron12+
