### ISSUE TITLE
 @electron/remote >= 2.x is required for Electron >= 14.

### ISSUE THREAD

**Issue by genzyy** [cba85/electron-webview#50]
I faced this issue when I cloned this repo, installed npm packages with `npm install`, and tried running this app with `npm start`.

For me , the issue got fixed when I bumped the `@electron/remote` package version to `2.0.1` specifically. Maybe we should bump up the version for @electron/remote package in the repo too?

OS: Windows 10
Terminal: Windows Command Line (Windows Terminal)
Node version: 16.13.0

**Comment by cba85** [comment]
Hello, right, this repository actually uses Electron.

Why don't you send me a pull request and I'll add your fixes?

**Comment by cba85** [comment]
Fixed. Please contribute to open-source projet instead stealing it.
