### ISSUE TITLE
New repo maintained here: https://github.com/genzyy/electron-webview

### ISSUE THREAD

**Issue by genzyy** [cba85/electron-webview#54]
- The [repo](https://github.com/genzyy/electron-webview) is maintained by me.
- Newer `electron` and `@electron/remote` versions
- Updated for better support.
- Open to contribution.
- Can be used as a template.

**Comment by cba85** [comment]
Hello,

this repository is maintained.

You've just steal my work without forking it or even sending a PR. Why don't you send me a pull request? 

The repo is open to contribution too.

**Comment by genzyy** [comment]
> Hello,
> 
> this repository is maintained.
> 
> You've just steal my work without forking it or even sending a PR. Why don't you send me a pull request?
> 
> The repo is open to contribution too.

Please get your facts right before attacking. Thank you
