### ISSUE TITLE
Content Protection | Screen Protection

### ISSUE THREAD

**Issue by abdulrehmanrfqt** [cba85/electron-webview#72]
where can I  setContentProtection in app

**Comment by cba85** [comment]
First, Hello, we're humans, not machines.

Then, it's not a question directly concerning my app, but Electron itself.

So, please read the docs: https://www.electronjs.org/fr/docs/latest/api/browser-window#winsetcontentprotectionenable-macos-windows. The docs gives you the solution (it's a method of BrowserWindow class).

In this project, BrowserWindow instance object is located in `/src/window.js` file.

Before using a langage, tool, framework... Please learn the fundamentals to basically understand how it works.
I'm sure you'll find good tutorials on internet. Here is the official tutorial made by Electron's team: https://www.electronjs.org/docs/latest/tutorial/tutorial-prerequisites

You seem to be a student developper. As a senior developper, I'm happy to help you. But, really, be a minimum polite and respectful when you ask for help, especially on an open-source projet.
