### ISSUE TITLE
APP first launch slow in MacOS

### ISSUE THREAD

**Issue by ThreeApples777** [cba85/electron-webview#88]
MacOS system, the first time to launch the APP is particularly slow, the icon will jump in the Dock for about 5 seconds before the APP will open.

**Comment by cba85** [comment]
First, hello (don't forget we're humans).

Then, it doesn't seems to be a problem that depends on my code.

If the app you've built using electron packager is slow to open on the first launch, it seems to be an architecture problem with [Electron packager](https://github.com/electron/electron-packager). Your Mac seems to convert your app using Rosetta on the first launch.

Do you have a M1/M2 Mac and use the command line written in `README.md` file or `$ npm run package-mac`?

```
$ npx electron-packager . --overwrite --platform=darwin --arch=x64 --icon=assets/icons/mac/icon.icns --prune=true --out=release-builds
```
In this case, don't use `--arch=x64` but use `--arch=arm64` instead (see https://electron.github.io/electron-packager/main/modules/electronpackager.html#officialarch).

You won't build an Electron app for Intel processors (x64) but for M1/M2 processors, and your Mac won't convert your x64 architecture app to arm64 architecture on first launch.
