### ISSUE TITLE
Right-Clicks Disallowed default

### ISSUE THREAD

**Issue by Nateraa** [cba85/electron-webview#95]
Hello!

How I could allow right clicks / grant access to clipboard in my electronJS webview app, my website uses right click to for its correct operation.

Thanks in advance.

**Comment by cba85** [comment]
Hello,

I'm sorry but it's not an issue specific to this Electron webview starter kit. It's an Electron issue. 
Electron doesn't have a built-in context menu.

Maybe check [Electron Context Menu](https://github.com/sindresorhus/electron-context-menu)

> Electron doesn't have a built-in context menu. You're supposed to handle that yourself. But it's both tedious and hard to get right. This module gives you a nice extensible context menu with spellchecking and items like Cut/Copy/Paste for text, Save Image for images, and Copy Link for links. It also adds an Inspect Element menu item when in development to quickly view items in the inspector like in Chrome.
